# Generated by Django 3.2.12 on 2022-04-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='district',
            field=models.IntegerField(choices=[(1, 'North'), (2, 'Center'), (3, 'Jerusalem'), (4, 'South')], default=3),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='east_loc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='min_till_doctor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='north_loc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
